// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyF8azYwJQEt5DsNicA_6GwRkCBsyrlY',
    appId: '1:407684585418:web:581cbdfa890535db69a133',
    messagingSenderId: '407684585418',
    projectId: 'maggot-plasma',
    authDomain: 'maggot-plasma.firebaseapp.com',
    storageBucket: 'maggot-plasma.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfq923KK_SPY85E2TDukZsZQy0viIaivw',
    appId: '1:407684585418:android:86d7af33ffe2a9f969a133',
    messagingSenderId: '407684585418',
    projectId: 'maggot-plasma',
    storageBucket: 'maggot-plasma.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtugyjYQxLyKpTEaSlw9x8OkVqSOR_NjI',
    appId: '1:407684585418:ios:ee8df154e634e64969a133',
    messagingSenderId: '407684585418',
    projectId: 'maggot-plasma',
    storageBucket: 'maggot-plasma.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMaggot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtugyjYQxLyKpTEaSlw9x8OkVqSOR_NjI',
    appId: '1:407684585418:ios:ee8df154e634e64969a133',
    messagingSenderId: '407684585418',
    projectId: 'maggot-plasma',
    storageBucket: 'maggot-plasma.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMaggot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyF8azYwJQEt5DsNicA_6GwRkCBsyrlY',
    appId: '1:407684585418:web:698378fbf6de6da069a133',
    messagingSenderId: '407684585418',
    projectId: 'maggot-plasma',
    authDomain: 'maggot-plasma.firebaseapp.com',
    storageBucket: 'maggot-plasma.firebasestorage.app',
  );
}
