name: Auto Panen Harian

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cek-panen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install firebase-admin
      - run: node scripts/auto_panen.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}